# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490088215e5a18d6b18bdcf536ab1685d0e4524c2c9d301155334fbf4eb6a60db8e120a6164431fabb9d5bf2349ebf46080e15bdf6c633583af89c87f09d1b05

test:
  secret_key_base: e7830fe3f76ed55a6ed25535bd4269abecab9c4a8a9cc610407e4cd8cbc474843c94e245429c8b7328c415f6c30b40dbfda7b2acf2992d2158d88e9feef84d51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
